(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (global = typeof globalThis !== 'undefined' ? globalThis : global || self, (global.wakaka = global.wakaka || {}, global.wakaka.umd = global.wakaka.umd || {}, global.wakaka.umd.js = factory()));
})(this, (function () { 'use strict';

  var WakakaButton = {
  render: function(){var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('button',{staticClass:"button"},[_vm._v("click me")])},
  staticRenderFns: [],
    name: 'WakakaButton'
  };

  WakakaButton.install = function (Vue) {
    Vue.component(WakakaButton.name, WakakaButton);
  };

  var WakakaTable = {
  render: function(){var _vm=this;var _h=_vm.$createElement;_vm._self._c||_h;return _vm._m(0)},
  staticRenderFns: [function(){var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('table',[_c('th',[_vm._v("表头")]),_c('tr',[_c('td',[_vm._v("333")])])])}],
    name: 'WakakaTable'
  };

  WakakaTable.install = function (Vue) {
    Vue.component('WakakaTable', WakakaTable);
  };

  var WakakaUpload = {
  render: function(){var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c("div")},
  staticRenderFns: [],
      name: 'WakakaUpload'
    };

  WakakaUpload.install = function (Vue) {
    Vue.component('WakakaUpload', WakakaUpload);
  };

  /* Automatically generated by './build/bin/build-entry.js' */
  const components = [WakakaButton, WakakaTable, WakakaUpload];

  const install = function (Vue, opts = {}) {
    components.forEach(component => {
      console.log('component', component);
      Vue.component(component.name, component);
    });
    /* Vue.use(InfiniteScroll);
    Vue.use(Loading.directive); */

    Vue.prototype.$Wakaka = {
      size: opts.size || '',
      zIndex: opts.zIndex || 2000
    };
  };
  /* istanbul ignore if test*/


  if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
  }

  var index = {
    version: '1.0.0',
    install,

    /* 
      locale: locale.use,
      i18n: locale.i18n, 
      Loading,
    */
    Button: WakakaButton,
    Table: WakakaTable,
    Upload: WakakaUpload
  };

  return index;

}));
