
/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Table from '../packages/table/index.js';
import Upload from '../packages/upload/index.js';

const components = [
    Button,
  Table,
  Upload
];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    console.log('component', component)
    Vue.component(component.name, component);
  });

  /* Vue.use(InfiniteScroll);
  Vue.use(Loading.directive); */

  Vue.prototype.$Wakaka = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

};

/* istanbul ignore if test*/
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  /* 
    locale: locale.use,
    i18n: locale.i18n, 
    Loading,
  */
    Button,
  Table,
  Upload
};
